### ISSUE TITLE
Unable to locate a class or view for component [lang-switcher]. 

### ISSUE THREAD

**Issue by thyseus** [lara-zeus/core#14]
Since the newest update i get the message:
```
Unable to locate a class or view for component [lang-switcher]. 
(View: /var/www/html/vendor/lara-zeus/core/resources/views/components/app.blade.php)
```

removing the `<x-lang-switcher/>` from the view fixes the problem temporarily.

Probably someone forgot a `git add`? :)

**Comment by atmonshi** [comment]
sorry for that, the lang-switcher was for the demo app, but accidentally put it here :)

fixing it now
